sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
os:
  - linux
  - osx
env:
  - LETS_PREVIEW_ENDPOINT="https://api.alpha.letspreview.io" LETS_PREVIEW_API_KEY="cj6uxivyp00003i5y97hv09ya"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - yarn run lint
  - npm test
after_success:
  - npm run report-coverage
  - npm run semantic-release
notifications:
  email: change
